name: Deploy Nimbus Cloud

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            set -e
            cd ~/cloud-portfolio-dashboard

            git fetch origin
            git reset --hard origin/master

            docker compose down

            docker compose up -d --build --remove-orphans

            docker image prune -af